version: '2'


services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    networks:
      - cicd-network

  apache:
    build:
      context: .
      dockerfile: /dockerfile-apache/Dockerfile
    image: httpd
    ports:
      - 90:80
    networks:
      - cicd-network

networks:
  cicd-network: {}