version: '2'


services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    networks:
      - cicd-network

  apache:
    image: httpd
    ports:
      - 80:80
    networks:
      - cicd-network

networks:
  cicd-network: {}